version: "3.8"

services:
  base:
    extra_hosts:
      - qi-policy.localtest.me:188.0.0.2

  backend:
    extends: base
    environment:
      MONGODB_PROTOCOL: 'mongodb'
      MONGODB_PASSWORD: admin
      MONGODB_USERNAME: admin
      NODE_ENV: dev
      VIRTUAL_PORT: 8080
    networks:
      - default
      - proxy